env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
parserOptions:
  commonJS: latest
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
