import React, { type ReactNode } from 'react'
export const metadata = {
  title: 'Calculadora_Next',
  description: 'Generated by Next.js'
}

interface Props {
  children: ReactNode
}

export default function RootLayout ({ children }: Props): JSX.Element {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
